spring.application.name=core-app
spring.datasource.url=jdbc:postgresql://localhost:5432/spo-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
imagekit.public.key=public_wLuNfiIHQgIW2iCaxcnX8vM2cXg=
imagekit.private.key=private_G4aWnC4cwmrbzt61I1Hh9UzU/6g=
imagekit.endpoint=https://ik.imagekit.io/pbihdph3e
spring.mail.host=smtp.gmail.com
spring.mail.port=587
token.secret.password=bcjevcjevcjevbcvhevcegvhgevchevjvejbudbwcbwjdbwdjxjkwgwgdjwbcjevejcvbejvcevfcvueb
spring.mail.username=6206472735rahul@gmail.com
spring.mail.password=ceffelhhjfderwei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
